title: Truepositive.hu Smart Cameras
description: > # this means to ignore newlines until "baseurl:"
    Developing COVID-19 Fever Detector and People Counter IoT Edge devices
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://truepositive.hu" # the base hostname & protocol for your site
permalink: "/:title/"

author: zoltanszalontay

email: zoltansz@truepositive.eu
facebook_page: zoltan.szalontay
twitter_username: zoltanszalontay
github_username:  zoltanszalontay
instagram_username: zoltanszalontay
linkedin_username: zoltanszalontay
youtube_channel: channel/UCrExDu53VZS2y1KGHny0QOA

# 
google_analytics: UA-181492090-1

plugins:
    - jekyll-sitemap

exclude: [node_modules, .gulpfile.js, package.json, docs, vendor/bundle, _sass]
