title: truepositive.hu
description: > # this means to ignore newlines until "baseurl:"
    Finding technolgy solutions to business problems. Developing IoT Edge solutions and Machine Learning algorithms on the Edge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://truepositive.hu" # the base hostname & protocol for your site
permalink: "/:title/"

author: zoltanszalontay

email: zoltansz@truepositive.eu
facebook_page: zoltan.szalontay
twitter_username: zoltanszalontay
github_username:  zoltanszalontay
instagram_username: zoltanszalontay
linkedin_username: zoltanszalontay
youtube_channel: zoltanszalontay # UCrExDu53VZS2y1KGHny0QOA

google_analytics: 

plugins:
    - jekyll-sitemap

exclude: [node_modules, .gulpfile.js, package.json, docs, vendor/bundle, _sass]
