title: truepositive.eu
description: > # this means to ignore newlines until "baseurl:"
    Long description. TBD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://truepositive.eu" # the base hostname & protocol for your site
permalink: "/:title/"

author: zoltanszalontay

email: zoltansz@truepositive.eu

twitter_username: zoltanszalontay
github_username:  zoltanszalontay
facebook_page: zoltanszalontay
instagram_username: zoltanszalontay
linkedin_username: zoltan.szalontay62
youtube_channel: zoltan.szalontay

disqus: zoltansz
google_analytics: 

plugins:
    - jekyll-sitemap

exclude: [node_modules, .gulpfile.js, package.json, docs, vendor/bundle, _sass]

theme: jekyll-theme-time-machine